// Reptile sprite data for LVGL
// Generated pixel art sprites in RGB565 format
// Each sprite is 64x48 pixels

#include "lvgl.h"

// Color definitions (RGB565)
#define C_TRANS   0x0000  // Transparent (will use color key)
#define C_BLACK   0x0000
#define C_WHITE   0xFFFF
#define C_GREEN1  0x2E8A  // Dark green (body)
#define C_GREEN2  0x3ECA  // Medium green (body highlight)
#define C_GREEN3  0x5F2B  // Light green (belly)
#define C_BROWN   0x6B4D  // Brown (spots)
#define C_ORANGE  0xFC00  // Orange (eyes/accents)
#define C_RED     0xF800  // Red (sick indicator)
#define C_YELLOW  0xFFE0  // Yellow (happy)
#define C_GRAY    0x7BEF  // Gray (sleeping)
#define C_PINK    0xF81F  // Pink (tongue)

// Sprite: Idle pose 1
static const uint16_t reptile_idle_data[] = {
    // Row 0-15: Empty space above reptile
    #define ROW_EMPTY C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS, \
                      C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS, \
                      C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS, \
                      C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS, \
                      C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS, \
                      C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS, \
                      C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS, \
                      C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS

    // Rows 0-11: Empty
    ROW_EMPTY, ROW_EMPTY, ROW_EMPTY, ROW_EMPTY,
    ROW_EMPTY, ROW_EMPTY, ROW_EMPTY, ROW_EMPTY,
    ROW_EMPTY, ROW_EMPTY, ROW_EMPTY, ROW_EMPTY,

    // Row 12-15: Head starts
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Row 13: Head with eye
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,
    C_GREEN2,C_WHITE,C_BLACK,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN1,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Row 14: Head continues
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN3,C_GREEN3,C_GREEN3,
    C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN1,C_GREEN1,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Row 15: Neck/body transition
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,
    C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Rows 16-23: Body
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,
    C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN3,C_GREEN3,C_BROWN,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN1,C_GREEN1,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN2,
    C_GREEN2,C_GREEN2,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_BROWN,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN1,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Body middle with spots
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,
    C_GREEN2,C_GREEN3,C_GREEN3,C_GREEN3,C_BROWN,C_GREEN3,C_GREEN3,C_GREEN3,
    C_GREEN3,C_BROWN,C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    C_TRANS,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_BROWN,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Body continues
    C_TRANS,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,
    C_BROWN,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,
    C_GREEN2,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Body lower
    C_TRANS,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,
    C_GREEN2,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Legs and tail start
    C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,
    C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Front leg
    C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN1,C_GREEN1,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,
    C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Belly and legs
    C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_TRANS,C_GREEN2,C_GREEN2,C_GREEN3,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,
    C_GREEN3,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,
    C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_GREEN1,
    C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Feet
    C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_GREEN2,C_GREEN2,
    C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN2,
    C_GREEN2,C_GREEN2,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_GREEN1,C_GREEN1,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Tail section
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_GREEN2,
    C_GREEN2,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN3,C_GREEN2,C_GREEN2,
    C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_GREEN1,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Tail continues
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_GREEN1,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN2,C_GREEN1,C_GREEN1,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Tail end
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_GREEN1,C_GREEN1,C_GREEN2,C_GREEN1,C_GREEN1,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_GREEN1,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,
    C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,C_TRANS,

    // Remaining empty rows
    ROW_EMPTY, ROW_EMPTY, ROW_EMPTY, ROW_EMPTY,
    ROW_EMPTY, ROW_EMPTY, ROW_EMPTY, ROW_EMPTY,
    ROW_EMPTY, ROW_EMPTY, ROW_EMPTY, ROW_EMPTY,
    ROW_EMPTY, ROW_EMPTY, ROW_EMPTY, ROW_EMPTY,
    ROW_EMPTY, ROW_EMPTY, ROW_EMPTY

    #undef ROW_EMPTY
};

// LVGL image descriptor for idle sprite
const lv_image_dsc_t img_reptile_idle = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = REPTILE_SPRITE_WIDTH,
        .h = REPTILE_SPRITE_HEIGHT,
    },
    .data_size = REPTILE_SPRITE_WIDTH * REPTILE_SPRITE_HEIGHT * 2,
    .data = (const uint8_t *)reptile_idle_data,
};

// Idle pose 2 (slight variation for animation)
const lv_image_dsc_t img_reptile_idle2 = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = REPTILE_SPRITE_WIDTH,
        .h = REPTILE_SPRITE_HEIGHT,
    },
    .data_size = REPTILE_SPRITE_WIDTH * REPTILE_SPRITE_HEIGHT * 2,
    .data = (const uint8_t *)reptile_idle_data,  // Same data for now
};

// Hungry sprite (uses same base with overlay handled in code)
const lv_image_dsc_t img_reptile_hungry = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = REPTILE_SPRITE_WIDTH,
        .h = REPTILE_SPRITE_HEIGHT,
    },
    .data_size = REPTILE_SPRITE_WIDTH * REPTILE_SPRITE_HEIGHT * 2,
    .data = (const uint8_t *)reptile_idle_data,
};

// Sick sprite
const lv_image_dsc_t img_reptile_sick = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = REPTILE_SPRITE_WIDTH,
        .h = REPTILE_SPRITE_HEIGHT,
    },
    .data_size = REPTILE_SPRITE_WIDTH * REPTILE_SPRITE_HEIGHT * 2,
    .data = (const uint8_t *)reptile_idle_data,
};

// Happy sprite
const lv_image_dsc_t img_reptile_happy = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = REPTILE_SPRITE_WIDTH,
        .h = REPTILE_SPRITE_HEIGHT,
    },
    .data_size = REPTILE_SPRITE_WIDTH * REPTILE_SPRITE_HEIGHT * 2,
    .data = (const uint8_t *)reptile_idle_data,
};

// Sleeping sprite
const lv_image_dsc_t img_reptile_sleeping = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = REPTILE_SPRITE_WIDTH,
        .h = REPTILE_SPRITE_HEIGHT,
    },
    .data_size = REPTILE_SPRITE_WIDTH * REPTILE_SPRITE_HEIGHT * 2,
    .data = (const uint8_t *)reptile_idle_data,
};

// Eating sprite
const lv_image_dsc_t img_reptile_eating = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = REPTILE_SPRITE_WIDTH,
        .h = REPTILE_SPRITE_HEIGHT,
    },
    .data_size = REPTILE_SPRITE_WIDTH * REPTILE_SPRITE_HEIGHT * 2,
    .data = (const uint8_t *)reptile_idle_data,
};

// Dead sprite
const lv_image_dsc_t img_reptile_dead = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .w = REPTILE_SPRITE_WIDTH,
        .h = REPTILE_SPRITE_HEIGHT,
    },
    .data_size = REPTILE_SPRITE_WIDTH * REPTILE_SPRITE_HEIGHT * 2,
    .data = (const uint8_t *)reptile_idle_data,
};
